CREATE TABLE CLIENTE (
	cliente_id INTEGER NOT NULL,
	nombres VARCHAR2(150) NOT NULL,
	apellidos VARCHAR2(150) NOT NULL,
	dni VARCHAR2(8) NOT NULL,
	telefono VARCHAR2(40) NULL,
	email VARCHAR2(100) NULL,
	PRIMARY KEY(cliente_id)
);
CREATE TABLE "VENTA" (
    venta_id INTEGER NOT NULL,
	fecha DATE NOT NULL,
	CLIENTE_id INTEGER NULL,
	PRIMARY KEY(venta_id)
);
CREATE TABLE "PRODUCTO" (
	producto_id INTEGER NOT NULL,
	nombre VARCHAR2(120) NOT NULL,
	precio NUMBER(10,2) NOT NULL,
	PRIMARY KEY(producto_id)
);
CREATE TABLE "DETALLE_VENTA" (
    detalle_venta_id INTEGER NOT NULL,
    cantidad INTEGER NOT NULL,
	venta_id INTEGER NULL,
	producto_id INTEGER NULL,
    PRIMARY KEY(detalle_venta_id)
);

-- GENERANDO RELACIONES
ALTER TABLE "VENTA" ADD CONSTRAINT "venta_cliente_cliente_id" FOREIGN KEY (CLIENTE_id) REFERENCES "CLIENTE"(cliente_id) ;
ALTER TABLE "DETALLE_VENTA" ADD CONSTRAINT "detalle_venta_venta_venta_id" FOREIGN KEY (VENTA_id) REFERENCES "VENTA"(venta_id) ;
ALTER TABLE "DETALLE_VENTA" ADD CONSTRAINT "detalle_venta_producto_produc3" FOREIGN KEY (PRODUCTO_id) REFERENCES "PRODUCTO"(producto_id) ;


CREATE SEQUENCE client_seq START WITH 1;
CREATE SEQUENCE venta_seq START WITH 1;
CREATE SEQUENCE producto_seq START WITH 1;
CREATE SEQUENCE detalleventa_seq START WITH 1;
